extends SceneTree

## godot --headless --script harness/generate_matrix.gd -- --out harness/loadouts.toml --total 50 --seed 1
##
## Generates the loadout matrix docs/plan.md calls for: every legal
## uniform-tier combination (one build per tier, all four slots matched),
## plus a seeded-random sample of mixed-tier builds, up to --total entries.
## Run once and commit the result under version control like any other
## generated-not-hand-written artefact — sweep.gd reads the committed file,
## it does not regenerate the matrix on every invocation.
##
## tools/toml.gd has no array-of-tables ([[x]]) support, so each loadout is
## its own dotted section — [loadout.<key>] — which the existing parser
## already handles as a nested table.

const DataLoader = preload("res://tools/data_loader.gd")
const Loadout = preload("res://sim/loadout.gd")
const Rng = preload("res://sim/rng.gd")

const SLOTS := ["feed", "chamber", "cooling", "targeting"]

func _init() -> void:
	var args := _parse_args(OS.get_cmdline_user_args())
	var out_path: String = args.get("out", "harness/loadouts.toml")
	var total := int(args.get("total", "50"))
	var seed_val := int(args.get("seed", "1"))

	var data := DataLoader.load_all()
	var modules_by_id: Dictionary = data["modules"]
	var tuning: Dictionary = data["tuning"]

	var by_slot_by_tier := {}
	for slot in SLOTS:
		by_slot_by_tier[slot] = {}
	for id in modules_by_id.keys():
		var mod: Dictionary = modules_by_id[id]
		var slot := String(mod.get("slot", ""))
		var tier := int(mod.get("tier", 0))
		if by_slot_by_tier.has(slot):
			(by_slot_by_tier[slot] as Dictionary)[tier] = id

	var tiers: Array = (by_slot_by_tier[SLOTS[0]] as Dictionary).keys()
	tiers.sort()

	var loadouts: Array = []
	var seen := {}

	for tier in tiers:
		var ok := true
		var modules: Array = []
		for slot in SLOTS:
			var tier_map: Dictionary = by_slot_by_tier[slot]
			if not tier_map.has(tier):
				ok = false
				break
			modules.append(tier_map[tier])
		if ok:
			_add_if_legal(loadouts, seen, modules, modules_by_id, tuning, "uniform_t%d" % tier)

	var rng := Rng.new(seed_val)
	var guard := 0
	while loadouts.size() < total and guard < total * 50:
		guard += 1
		var modules: Array = []
		for slot in SLOTS:
			var tier_map: Dictionary = by_slot_by_tier[slot]
			var tier_keys: Array = tier_map.keys()
			modules.append(tier_map[tier_keys[rng.next_below(tier_keys.size())]])
		_add_if_legal(loadouts, seen, modules, modules_by_id, tuning, "mixed_%03d" % loadouts.size())

	_write_matrix(out_path, loadouts)
	print("wrote %d loadouts to %s" % [loadouts.size(), out_path])
	quit(0)

func _add_if_legal(loadouts: Array, seen: Dictionary, modules: Array, modules_by_id: Dictionary, tuning: Dictionary, key: String) -> void:
	var dedupe_key: String = ",".join(modules)
	if seen.has(dedupe_key):
		return
	var assembled := Loadout.assemble(modules, modules_by_id, tuning)
	if not assembled["ok"]:
		return
	seen[dedupe_key] = true
	loadouts.append({"key": key, "modules": modules})

func _write_matrix(path: String, loadouts: Array) -> void:
	var lines: PackedStringArray = []
	lines.append("# Generated by harness/generate_matrix.gd — do not hand-edit.")
	lines.append("# Regenerate with: godot --headless --script harness/generate_matrix.gd -- --out %s" % path)
	for entry in loadouts:
		var quoted: Array = []
		for m in entry["modules"]:
			quoted.append('"%s"' % m)
		lines.append("")
		lines.append("[loadout.%s]" % entry["key"])
		lines.append("modules = [%s]" % ", ".join(quoted))
	var f := FileAccess.open(path, FileAccess.WRITE)
	f.store_string("\n".join(lines) + "\n")

func _parse_args(raw: PackedStringArray) -> Dictionary:
	var result := {}
	var i := 0
	while i < raw.size():
		var token: String = raw[i]
		if token.begins_with("--"):
			var key := token.substr(2)
			if i + 1 < raw.size() and not raw[i + 1].begins_with("--"):
				result[key] = raw[i + 1]
				i += 2
			else:
				result[key] = true
				i += 1
		else:
			i += 1
	return result
